name: vjepa2-amd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - av==16.1.0
      - babel==2.17.0
      - beartype==0.22.9
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - braceexpand==0.1.7
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - einops==0.8.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fire==0.7.1
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - markdown==3.10.1
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - mpmath==1.3.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - notebook==7.5.2
      - notebook-shim==0.2.4
      - numpy==2.3.5
      - omegaconf==2.3.0
      - opencv-python==4.13.0.90
      - packaging==26.0
      - pandas==3.0.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - peft==0.18.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - portalocker==3.2.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytorch-triton-rocm==3.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scipy==1.17.0
      - send2trash==2.1.0
      - sentry-sdk==2.50.0
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - submitit==1.5.4
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - terminado==0.18.1
      - tifffile==2026.1.14
      - timm==1.0.24
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - torch==2.5.1+rocm6.2
      - torchaudio==2.5.1+rocm6.2
      - torchvision==0.20.1+rocm6.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.6
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - vjepa2==0.0.1
      - wandb==0.24.0
      - wcwidth==0.3.0
      - webcolors==25.10.0
      - webdataset==1.0.2
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
prefix: /home/sharon/miniconda3/envs/vjepa2-amd
